In [ ]:
print('sunnyleone')

sunnyleone

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [ ]:
dic={'area':[2600,3000,3200,3600,4000],
     'bedrooms':[3,4,None,3,5],
'age':[20,15,18,30,8],
'price':[550000,565000,610000,595000,760000]}
df=pd.DataFrame(dic)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
a=df['bedrooms']
a=a.median()
a=int(a)
a

3

In [ ]:
df=df.fillna(a)
df

   area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
lreg=LinearRegression()
lreg.fit(df[['area','bedrooms','age']],df[['price']])
y_pred=lreg.predict(df[['area','bedrooms','age']])
print(y_pred)                                     #  dependent  =   m*independents +   intercept
print(lreg.coef_)                                 #  y=  m1*x1  +  m2*x2  +  m3*x3   + C
print(lreg.intercept_)                            #  526000 =137.25*(2600)+(-26025.)*(3.0)+(-6825.)*20 + 383725.

[[526000.]
 [589000.]
 [622000.]
 [595000.]
 [748000.]]
[[   137.25 -26025.    -6825.  ]]
[383725.]

In [ ]:
137.25*(2600)+(-26025.)*(3.0)+(-6825.)*20 + 383725.

526000.0

**Exercise also in this notebook**

In [ ]:
!curl 'https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv' -o hiring.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   189  100   189    0     0    448      0 --:--:-- --:--:-- --:--:--   447

In [ ]:
df=pd.read_csv('/content/hiring.csv')
exp=df[['experience']].fillna('zero')
df=df.iloc[:,1:]
df=exp.join(df)
test='test_score(out of 10)'
df[test]=df[test].fillna(df[test].median())
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    8.0                           7      72000
7     eleven                    7.0                           8      80000

if you want to change a column in dataframe then simple way is 
#df['column']=df['column'].fillna(100)

better use word to number to convert the words to numbers

In [ ]:
li=[0,0,5,2,7,3,10,11]
newdf=pd.DataFrame(li,columns=['experience'])
df=newdf.join(df.iloc[:,1:])
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [ ]:
lreg2=LinearRegression()
x=df.iloc[:,:3]
y=df.iloc[:,3:]
lreg2.fit(x,y)
lreg2.predict(x)

array([[52350.0727802 ],
       [45734.35225619],
       [58312.95487627],
       [63872.63464338],
       [67270.74235808],
       [61148.47161572],
       [76069.1411936 ],
       [79241.63027656]])

In [ ]:
lreg2.predict([[2,9,6]])

array([[53205.96797671]])

In [ ]:
lreg2.predict([[12,10,10]])

array([[92002.18340611]])

In [ ]:
import pickle

In [ ]:
with open('model','wb') as f:          #here model is as filename,lreg2 is oject containing our model
     pickle.dump(lreg2,f)

In [ ]:
with open('model','rb') as f:           #here 'model' is MODEL we saved and we reading into object model
      model=pickle.load(f)

In [ ]:
model.predict([[12,10,10]])

array([[92002.18340611]])

In [ ]:
from sklearn.externals import joblib

In [ ]:
joblib.dump(lreg2,'lregmodel.pkl')

['lregmodel.pkl']

In [ ]:
jmodel=joblib.load('lregmodel.pkl')

In [ ]:
jmodel.predict([[12,10,10]])

array([[92002.18340611]])